CSCvw85868 Warning in aim-aid logs about default OOB contract
noironetworks/aci-integration-module pull request #325
Opened 2021-02-12 02:08 UTC by sbagalur

Adding Out of Band Contract MO

2021-04-08 10:52 UTC, tbachman commented
Two change requests:
1) squash the commits
2) rebase your patch on master (will pick up the fixes for the TravisCI failures)

2021-04-16 17:59 UTC, tbachman requested changes
Some minor changes. Also - as an open source project, the commit message shouldn't reference Cisco CDETs, and the commit message should reflect the nature of the change (i.e. "Add support for out of band contracts

Support is added for converting and configuration of out of band contracts in AIM. This addresses errors seen in the aim-aid logs, where out of band contracts fail in the converter").

2021-04-16 18:24 UTC, sbagalur commented
> Some minor changes. Also - as an open source project, the commit message shouldn't reference Cisco CDETs, and the commit message should reflect the nature of the change (i.e. "Add support for out of band contracts
> 
> Support is added for converting and configuration of out of band contracts in AIM. This addresses errors seen in the aim-aid logs, where out of band contracts fail in the converter").

2021-04-25 14:15 UTC, tbachman approved these changes

2021-04-25 14:15 UTC, merged