Apic Client Fix
noironetworks/aci-integration-module pull request #357
Opened 2022-06-22 01:29 UTC by sayalinaval

Change-Id: Ia017bfdae7397a89b1295877d59188532700c20a

2022-08-14 15:34 UTC, irathore approved these changes

2022-08-14 18:00 UTC, tbachman commented
Please squash the commits.

2022-08-16 00:55 UTC, tbachman requested changes
Overall, a really clean patch. Just a couple of comments.

2022-08-16 00:55 UTC, tbachman commented on aim/agent/aid/universes/aci/tenant.py
> +        ws_context.establish_aci_session()
Is this needed? Isn't the session established already in the WebSocketContext class?

2022-08-16 00:55 UTC, tbachman commented on aim/agent/aid/universes/aci/tenant.py
> +        self.ws_context.establish_aci_session()
Same comment as above.

2022-08-30 10:54 UTC, tbachman commented on aim/agent/aid/universes/aci/tenant.py
> +        ac_subscription_to = kwargs.pop('ac_subscription_to')
I think you can leave this one as ws_subscription_to - this applies only to the websocket client, right?

2022-08-30 10:55 UTC, tbachman commented on aim/agent/aid/universes/aci/tenant.py
> +        ac_subscription_to = self.apic_config.get_option(
same comment here

2022-08-30 10:55 UTC, tbachman requested changes
Minor nit/change.

2022-09-05 09:53 UTC, tbachman commented
Please back out OpenSSL change and squash commits, then rebase.

2022-11-11 17:30 UTC, merged