Normalization of Remote IP feature support
noironetworks/aci-integration-module pull request #393
Opened 2023-10-30 19:00 UTC by sbagalur

This patch adds support for Normalization of Remote IP feature support

2023-11-10 00:56 UTC, tbachman requested changes
Great patch! Nearly there - just a few things to look at.

2023-11-11 00:14 UTC, sbagalur commented on aim/agent/aid/universes/aci/tenant.py
> +def supports_remoteIPContainer(apic_session):
Will move the function to aci_universe.py. I did add it as a resouce under aim/api/infra.py. Since it was more infra related.

2023-11-11 00:14 UTC, sbagalur commented on aim/agent/aid/universes/aci/tenant.py
> +        support_mo_mgr = aim_infra_model.ACISupportedMoManager(aim_ctx,
Will check on this

2023-11-11 00:17 UTC, sbagalur commented on aim/agent/aid/universes/aci/tenant.py
> +def supports_remoteIPContainer(apic_session):
I updated the DB directly, since the DB migration already created the row in the DB, and it was only updating the boolean.

2023-11-13 05:06 UTC, tbachman commented on aim/agent/aid/universes/aci/tenant.py
> +        support_mo_mgr = aim_infra_model.ACISupportedMoManager(aim_ctx,
I'm fine with addressing it in a separate patch.

2023-11-13 19:45 UTC, sbagalur commented on aim/agent/aid/universes/aci/tenant.py
> +        support_mo_mgr = aim_infra_model.ACISupportedMoManager(aim_ctx,
Sounds good.

2023-11-13 22:34 UTC, closed without merging