Fixing static analysis vulnerabilities for aim
noironetworks/aci-integration-module pull request #415
Opened 2024-05-16 22:59 UTC by sbagalur

Fixing the static analysis vulnerabilities that were reported through bandit runs/ marking the false positives.

2024-05-17 11:44 UTC, tbachman approved these changes

2024-05-17 17:17 UTC, christides11 approved these changes

2024-05-20 17:25 UTC, tbachman commented on aim/agent/aid/universes/aci/aci_universe.py
>              pass
I think you can get rid off the pass statement here.

2024-05-20 17:25 UTC, tbachman commented on aim/agent/aid/universes/aci/tenant.py
>                  pass
same for here and the one below

2024-05-20 17:26 UTC, tbachman commented on aim/db/migration/data_migration/status_add_dn.py
> +                         "error: %s", str(e))
I think you can get rid of the pass statement here.

2024-05-20 17:26 UTC, tbachman requested changes
Some minor changes.

2024-05-20 20:27 UTC, tbachman approved these changes

2024-05-20 20:27 UTC, merged