Rebase SqlAlchemy_2.0 Support
noironetworks/aci-integration-module pull request #433
Opened 2024-11-28 05:18 UTC by nisar123456

2025-12-03 12:46 UTC, tbachman requested changes
I didn't look through the entire patch - there are a lot of cases where code that was previously safe under concurrency would no longer be protected. I'd like to get a better understanding of why the concurrency there was removed before going further in this patch.

2025-12-03 12:46 UTC, tbachman commented on aim/agent/aid/universes/aim_universe.py
> +        self.tree_manager.delete_by_root_rn(context, key, if_empty=True)
The previous patch called the parent class's cleanup_state method. Isn't that still needed here?

2025-12-03 12:46 UTC, tbachman commented on aim/agent/aid/service.py
> +        # Refresh this agent
I think this is a problem - the agent update is not scoped by a transaction any more, and therefore can't be atomic. What was the reason to remove the transaction here?

2025-12-03 12:46 UTC, tbachman commented on aim/agent/aid/universes/aim_universe.py
> +                if isinstance(resource, aim_resource.AciRoot):
Same concern here - the update is no longer atomic. What was the reason to remove the transaction?

2025-12-03 12:46 UTC, tbachman commented on aim/agent/aid/universes/aim_universe.py
> +                    existing = self.manager.get(context, resource)
And here - the get/delete code could be concurrent, and therefore needs the protection of a transaction.

2025-12-03 12:46 UTC, tbachman commented on aim/aim_lib/nat_strategy.py
> +        tenant = resource.Tenant(name=l3out.tenant_name)
Same concern here.

2025-12-03 14:59 UTC, nisar123456 commented on aim/agent/aid/universes/aim_universe.py
> +        self.tree_manager.delete_by_root_rn(context, key, if_empty=True)
yeah, parent class's cleanup_state method required. i will add it back

2025-12-03 15:01 UTC, nisar123456 commented on aim/agent/aid/service.py
> +        # Refresh this agent
All delete, create, and update operations are now handled within a single transaction, so we removed the additional transactions from other parts of the code. (self.manager handle all curd operation )

2026-05-05 12:15 UTC, tbachman approved these changes

2026-05-05 12:16 UTC, merged